# Generated by Django 3.2 on 2021-05-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='task',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='task',
        ),
    ]
